[package]
name = "GarminCycliqOverlay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpx = "0.8.6"
fitparser = "0.5.0"
chrono = "0.4"
image = "0.24.6"
opencv = "0.82.0"
ffprobe = "0.3.3"
